// React/src/DetailTemplate.tsx
import React, { useRef, useMemo, useCallback } from 'react';

import { DataGrid, Column } from 'devextreme-react/data-grid';
import type { DataGridRef, DataGridTypes } from 'devextreme-react/data-grid';
import Button from 'devextreme-react/button';
import { ArrayStore, DataSource } from 'devextreme-react/common/data';

import { tasks } from './data';

const buttonStyle = { marginBottom: 10 };

function getTasks(key: number) {
  return new DataSource({
    store: new ArrayStore({
      data: tasks,
      key: 'ID',
    }),
    filter: ['EmployeeID', '=', key],
  });
}

function DetailTemplate(props: DataGridTypes.MasterDetailTemplateData): JSX.Element {
  const detailGridInstance = useRef<DataGridRef>(null);

  const dataSource = useMemo(() => getTasks(props.data.key), [props.data.key]);

  const onButtonClick = useCallback(() => {
    detailGridInstance.current?.instance().option('focusedRowIndex', 0);
  }, []);

  return (
    <React.Fragment>
      <Button
        text='Focus row'
        onClick={onButtonClick}
        style={buttonStyle}
      />

      <DataGrid
        ref={detailGridInstance}
        dataSource={dataSource}
        showBorders={true}
        focusedRowEnabled={true}
      >
        <Column dataField='Subject' />
        <Column dataField='StartDate' />
        <Column dataField='DueDate' />
        <Column dataField='Priority' />
      </DataGrid>
    </React.Fragment>
  );
}

export default DetailTemplate;

// Vue/src/components/DetailTemplate.vue
<script setup lang="ts">
import { computed, ref } from 'vue';

import DxButton from 'devextreme-vue/button';
import DxDataGrid, { DxColumn, type DxDataGridTypes } from 'devextreme-vue/data-grid';
import { ArrayStore, DataSource } from 'devextreme-vue/common/data';

import { tasks } from '../data';

const props = defineProps<{
  data: DxDataGridTypes.MasterDetailTemplateData;
}>();

const detailGridInstance = ref<InstanceType<typeof DxDataGrid> | null>(null);

const dataSource = computed(() => new DataSource({
  store: new ArrayStore({
    data: tasks,
    key: 'ID',
  }),
  filter: ['EmployeeID', '=', props.data.key],
}));

function focusRow() {
  detailGridInstance.value?.instance?.option('focusedRowIndex', 0);
}
</script>

<template>
  <DxButton
    text="Focus row"
    :style="{ marginBottom: '10px' }"
    @click="focusRow"
  />

  <DxDataGrid
    ref="detailGridInstance"
    :data-source="dataSource"
    :show-borders="true"
    :focused-row-enabled="true"
  >
    <DxColumn data-field="Subject"/>
    <DxColumn data-field="StartDate"/>
    <DxColumn data-field="DueDate"/>
    <DxColumn data-field="Priority"/>
  </DxDataGrid>
</template>
