// vue/src/App.vue
<template>
  <dx-data-grid
    id="grid-container"
    :show-borders="true"
    :data-source="dataSource"
    key-expr="ID"
  >
    <dx-column
      :width="70"
      data-field="Prefix"
      caption="Title"
    />
    <dx-column data-field="FirstName"/>
    <dx-column data-field="LastName"/>
    <dx-column
      :width="170"
      data-field="Position"
    />
    <dx-column
      :width="125"
      data-field="State"
    />
    <dx-column
      data-field="BirthDate"
      data-type="date"
    />
    <dx-master-detail
      :enabled="true"
      template="masterDetailTemplate"
    />
    <div
      slot="masterDetailTemplate"
      slot-scope="employee"
    >
      <detail-template
        :template-data="employee"
      />
    </div>
  </dx-data-grid>
</template>
<script>
import {
  DxDataGrid,
  DxColumn,
  DxMasterDetail,
} from 'devextreme-vue/data-grid';

import DetailTemplate from './DetailTemplate.vue';
import service from './data.js';

const employees = service.getEmployees();

export default {
  components: {
    DxDataGrid,
    DxColumn,
    DxMasterDetail,
    DetailTemplate
  },
  data() {
    return {
      dataSource: employees
    };
  }
};
</script>
<style>
#grid-container {
    height: 440px;
}
</style>

// react/src/App.js
import React from 'react';

import DataGrid,
{
  Column,
  MasterDetail
} from 'devextreme-react/data-grid';

import DetailTemplate from './DetailTemplate.js';

import service from './data.js';

const employees = service.getEmployees();

class App extends React.Component {

  render() {
    return (
      <DataGrid id={'grid-container'}
        dataSource={employees}
        keyExpr={'ID'}
        showBorders={true}
      >
        <Column dataField={'Prefix'} width={70} caption={'Title'} />
        <Column dataField={'FirstName'} />
        <Column dataField={'LastName'} />
        <Column dataField={'Position'} width={170} />
        <Column dataField={'State'} width={125} />
        <Column dataField={'BirthDate'} dataType={'date'} />
        <MasterDetail
          enabled={true}
          component={DetailTemplate}
        />
      </DataGrid>
    );
  }
}

export default App;
