// react/src/DetailTemplate.js
import React from 'react';
import { Button } from 'devextreme-react/button';
import { DataGrid, Column } from 'devextreme-react/data-grid';
import ArrayStore from 'devextreme/data/array_store';
import DataSource from 'devextreme/data/data_source';
import service from './data.js';

const tasks = service.getTasks();

const getTasks = (key) => {
  return new DataSource({
    store: new ArrayStore({
      data: tasks,
      key: 'ID'
    }),
    filter: ['EmployeeID', '=', key]
  });
};

class DetailTemplate extends React.Component {
  constructor(props) {
    debugger;
    super(props);
    this.detailGrids = [];
    this.dataSource = getTasks(props.data.key);
    this.onClick = this.onClick.bind(this); 
  }
    
  onClick(e) {
    this.detailGrids[this.props.data.key].instance.option("focusedRowIndex", 0);
  }
    
  render() {
    return (
      <React.Fragment>
        <Button text={"Focus row"} onClick={this.onClick}></Button>
        <DataGrid ref={grid => this.detailGrids[this.props.data.key] = grid}
          dataSource={this.dataSource}
          showBorders={true}
          focusedRowEnabled={true}>
          <Column dataField={'Subject'} />
          <Column dataField={'StartDate'} dataType={'date'} />
          <Column dataField={'DueDate'} dataType={'date'} />
          <Column dataField={'Priority'} />
        </DataGrid>
      </React.Fragment>
    );
  }
}

export default DetailTemplate;

// vue/src/DetailTemplate.vue
<template>
  <div> 
      <dx-button
          text="Focus row"
          @click="buttonClick($event, key)"
        />
      
    <dx-data-grid
      :data-source="dataSource"
      :show-borders="true"
      :focused-row-enabled="true"
      :ref="'detailGrid' + key"
    >
      <dx-column data-field="Subject"/>
      <dx-column
        data-field="StartDate"
        data-type="date"
      />
      <dx-column
        data-field="DueDate"
        data-type="date"
      />
      <dx-column data-field="Priority"/>
    </dx-data-grid>
  </div>
</template>
<script>

import { DxButton } from 'devextreme-vue/button';
import { DxDataGrid, DxColumn } from 'devextreme-vue/data-grid';

import ArrayStore from 'devextreme/data/array_store';
import DataSource from 'devextreme/data/data_source';
import service from './data.js';

const tasks = service.getTasks();

export default {
  components: { DxButton, DxDataGrid, DxColumn },
  props: {
    templateData: {
      type: Object,
      default: ()=>{}
    }
  },
  data() {
    return {
      key: this.templateData.data.key,
      dataSource: this.getTasks(this.templateData.data.key)
    };
  },
  methods: {
    getTasks(key) {
      return new DataSource({
        store: new ArrayStore({
          data: tasks,
          key: 'ID'
        }),
        filter: ['EmployeeID', '=', key]
      });
    },
    buttonClick(e, key) {
      this.$refs[`detailGrid${key}`].instance.option("focusedRowIndex", 0);
    }
  }
};
</script>
<style>
.master-detail-caption {
    padding: 0 0 5px 10px;
    font-size: 14px;
    font-weight: bold;
}</style>
